# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import hyppo_pb2 as hyppo__pb2


class HyppoRemoteCollectorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendMonitorSample = channel.unary_unary(
        '/HyppoRemoteCollector/SendMonitorSample',
        request_serializer=hyppo__pb2.DataPoint.SerializeToString,
        response_deserializer=hyppo__pb2.Ack.FromString,
        )
    self.SendKubeSample = channel.unary_unary(
        '/HyppoRemoteCollector/SendKubeSample',
        request_serializer=hyppo__pb2.DataPoint.SerializeToString,
        response_deserializer=hyppo__pb2.Ack.FromString,
        )


class HyppoRemoteCollectorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SendMonitorSample(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendKubeSample(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HyppoRemoteCollectorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendMonitorSample': grpc.unary_unary_rpc_method_handler(
          servicer.SendMonitorSample,
          request_deserializer=hyppo__pb2.DataPoint.FromString,
          response_serializer=hyppo__pb2.Ack.SerializeToString,
      ),
      'SendKubeSample': grpc.unary_unary_rpc_method_handler(
          servicer.SendKubeSample,
          request_deserializer=hyppo__pb2.DataPoint.FromString,
          response_serializer=hyppo__pb2.Ack.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'HyppoRemoteCollector', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
