# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hyppo_remote_collector.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hyppo_remote_collector.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x1chyppo_remote_collector.proto\"\x1e\n\tDataPoint\x12\x11\n\tdatapoint\x18\x01 \x03(\t\"\x12\n\x03\x41\x63k\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\x08\x32\x65\n\x14HyppoRemoteCollector\x12\'\n\x11SendMonitorSample\x12\n.DataPoint\x1a\x04.Ack\"\x00\x12$\n\x0eSendKubeSample\x12\n.DataPoint\x1a\x04.Ack\"\x00\x62\x06proto3')
)




_DATAPOINT = _descriptor.Descriptor(
  name='DataPoint',
  full_name='DataPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='datapoint', full_name='DataPoint.datapoint', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=62,
)


_ACK = _descriptor.Descriptor(
  name='Ack',
  full_name='Ack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ack', full_name='Ack.ack', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=82,
)

DESCRIPTOR.message_types_by_name['DataPoint'] = _DATAPOINT
DESCRIPTOR.message_types_by_name['Ack'] = _ACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataPoint = _reflection.GeneratedProtocolMessageType('DataPoint', (_message.Message,), dict(
  DESCRIPTOR = _DATAPOINT,
  __module__ = 'hyppo_remote_collector_pb2'
  # @@protoc_insertion_point(class_scope:DataPoint)
  ))
_sym_db.RegisterMessage(DataPoint)

Ack = _reflection.GeneratedProtocolMessageType('Ack', (_message.Message,), dict(
  DESCRIPTOR = _ACK,
  __module__ = 'hyppo_remote_collector_pb2'
  # @@protoc_insertion_point(class_scope:Ack)
  ))
_sym_db.RegisterMessage(Ack)



_HYPPOREMOTECOLLECTOR = _descriptor.ServiceDescriptor(
  name='HyppoRemoteCollector',
  full_name='HyppoRemoteCollector',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=84,
  serialized_end=185,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendMonitorSample',
    full_name='HyppoRemoteCollector.SendMonitorSample',
    index=0,
    containing_service=None,
    input_type=_DATAPOINT,
    output_type=_ACK,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendKubeSample',
    full_name='HyppoRemoteCollector.SendKubeSample',
    index=1,
    containing_service=None,
    input_type=_DATAPOINT,
    output_type=_ACK,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_HYPPOREMOTECOLLECTOR)

DESCRIPTOR.services_by_name['HyppoRemoteCollector'] = _HYPPOREMOTECOLLECTOR

# @@protoc_insertion_point(module_scope)
